confd: add support for vendor/product specific factory-config
With the recent changes to confd to support: hostname format specifiers,
$factory$ default keyword for password, and on-the-fly generation of the
NETCONF SSH host keys, the system no longer depend on the very intricate
confd gen-* scripts to create factory-config and failure-config.

This patch set adds support for detecting and installing product/vendor
specific static factory-config and failure-config files.  See the confd
README for details.

To facilitate generation, e.g., of the NETCONF SSH host keys, the confd
daemon must be running when bootstrapping the first startup-config from
eithe generated or static factory-config.  This is why the bootstrap and
load helper scripts have been changed.

Signed-off-by: Joachim Wiberg <troglobit@gmail.com>

diff --git a/src/confd/bin/bootstrap b/src/confd/bin/bootstrap
--- a/src/confd/bin/bootstrap
+++ b/src/confd/bin/bootstrap
@@ -4,8 +4,8 @@
 ########################################################################
 # The system factory-config and failure-config are derived from default
 # settings snippets, from /usr/share/confd/factory.d, and some generated
-# snippets, e.g., device unique password, hostname (based on base MAC
-# address), and number of interfaces.
+# snippets, e.g., hostname (based on base MAC address) and number of
+# interfaces.
 #
 # The resulting factory-config is used to create the syrepo db (below)
 # {factory} datastore.  Hence, the factory-config file must match the
@@ -127,6 +127,8 @@ failure()
     collate "$FAILURE_GEN" "$FAILURE_CFG" "$FAILURE_D"
 }
 
+# Both factory-config and failure-config are generated every boot
+# regardless if there is a static /etc/factory-config.cfg or not.
 factory "$FACTORY_GEN"
 failure "$FAILURE_GEN"
 
@@ -143,24 +145,18 @@ else
 fi
 rc=$?
 
-sysrepoctl -z $INIT_DATA
-rc=$?
-sudo -u root -g wheel sysrepocfg -f json -I"$INIT_DATA" -d running
-rc=$?
-
-
-#rm $INIT_DATA
-
-# On first boot, install factory-config as startup-config.
-chgrp wheel /cfg
-chmod g+w   /cfg
-if [ ! -f "$STARTUP_CFG" ]; then
-    sysrepocfg -f json -X"$STARTUP_CFG"
+chgrp wheel "$CFG_PATH_"
+chmod g+w   "$CFG_PATH_"
+if ! sysrepoctl -z "$INIT_DATA"; then
+    rc=$?
+    logger -sik -p user.error "Failed loading factory-default datastore"
+else
+    # Clear running-config so we can load/create startup in the next step
+    temp=$(mktemp)
+    echo "{}" > "$temp"
+    sysrepocfg -f json -I"$temp" -d running
+    rc=$?
+    rm "$temp"
 fi
-
-# Clear running-config so we can load startup in the next step
-temp=$(mktemp)
-echo "{}" > $temp
-sysrepocfg -f json -I$temp -d running
 
 exit $rc
diff --git a/src/confd/bin/load b/src/confd/bin/load
--- a/src/confd/bin/load
+++ b/src/confd/bin/load
@@ -7,7 +7,6 @@
 # sysrepocfg returns OK.  This to be able to detect and trigger the Infix
 # Fail Secure Mode at boot.
 #
-set -e
 
 banner_append()
 {
@@ -17,6 +16,14 @@ banner_append()
 			  /etc/issue.net \
 			  >/dev/null
     return 0
+}
+
+# Ensure correct ownership and permissions, in particular after factory reset
+# Created by the system, writable by any user in the admin group.
+perms()
+{
+    chown root:wheel "$1"
+    chmod 0660 "$1"
 }
 
 note()
@@ -45,8 +52,21 @@ else
 fi
 
 if [ ! -f "$fn" ]; then
-    err "No such file, $fn, aborting!"
-    exit 1
+    case "$config" in
+	startup-config)
+	    note "startup-config missing, initializing running datastore from factory-config"
+	    sysrepocfg -C factory-default
+	    rc=$?
+	    note "saving factory-config to $STARTUP_CFG ..."
+	    sysrepocfg -f json -X"$STARTUP_CFG"
+	    perms "$STARTUP_CFG"
+	    exit $rc
+	    ;;
+	*)
+	    err "No such file, $fn, aborting!"
+	    exit 1
+	    ;;
+    esac
 fi
 
 note "Loading $config ..."
@@ -82,8 +102,5 @@ note "Loaded $fn successfully."
 if [ "$config" = "failure-config" ]; then
     banner_append "ERROR: Corrupt startup-config, system has reverted to default login credentials"
 else
-    # Ensure correct ownership and permissions, in particular after factory reset
-    # Created by the system, writable by any user in the admin group.
-    chown root:wheel "$fn"
-    chmod 0660 "$fn"
+    perms "$fn"
 fi
