confd: do not fail if pwhash is missing in VPD, instead lock account
If pwhash is missing from system.json, lock account.  This allows for
more extensive diagnosis on developer builds with a root login.

Signed-off-by: Joachim Wiberg <troglobit@gmail.com>

diff --git a/src/confd/bin/gen-admin-auth b/src/confd/bin/gen-admin-auth
--- a/src/confd/bin/gen-admin-auth
+++ b/src/confd/bin/gen-admin-auth
@@ -5,7 +5,12 @@ shell="$1"
 pwhash="$(jq .pwhash /run/system.json)"
 
 if [ -z "$pwhash" ] || [ "$pwhash" = "null" ]; then
-    exit 1
+    # Do not fail, lock account instead.  This way developers can enable
+    # root account login at build-tiem to diagnose the system.
+    pwhash="!"
+    rc=1
+else
+    rc=0
 fi
 
 cat <<EOF
@@ -23,3 +28,5 @@ cat <<EOF
   }
 }
 EOF
+
+exit $rc
