Use default pwd hash from VPD in QEMU
This commit does several things. Its end goal is to fetch the admin
password hash from VPD memory during factory bootstrap.

To accomplish this probe creates a new file /run/system.json with
information read from a fw_cfg QEMU partition. The data from
/run/system.json is then later used during config bootstrap to fill in
the factory administrator password.

The idea is to make QEMU behave the same way hardware does, i.e. a
default/factory password should be fetched and used from
"hardware memory". The hardware portion of this is yet to be done.

Signed-off-by: Richard Alpe <richard@bit42.se>

diff --git a/board/common/rootfs/lib/infix/probe b/board/common/rootfs/lib/infix/probe
--- a/board/common/rootfs/lib/infix/probe
+++ b/board/common/rootfs/lib/infix/probe
@@ -1,6 +1,35 @@
 #!/bin/sh
 # Probe for various types of harware features
 
-if dmesg |grep -q QEMU || test -d /sys/module/qemu_fw_cfg; then
-   initctl cond set qemu
+#TODO Rewrite this script in python before extending it further
+#TODO Remove fallback temporary development hash
+
+gen_qemu_system_file() {
+    vbd_json="$(onieprom /sys/firmware/qemu_fw_cfg/by_name/opt/vbd/raw)"
+    if [ $? -ne 0 ]; then
+        logger -p user.crit -t "probe" "Error, running onieprom tool"
+        exit 1
+    fi
+
+    pwhash="$(echo "$vbd_json" | jq -r '.["vendor-extension"][0][1]' | jq -r '.pwhash')"
+    if [ -z "$pwhash" ] || [ "$pwhash" = "null" ]; then
+        logger -p user.crit -t "probe" "Error, didn't find password hash"
+        exit 1
+    fi
+
+    system_json="$(echo "$vbd_json" | jq -r 'del(."vendor-extension")')"
+    system_json="$(echo "$system_json" | jq --arg val "$pwhash" '. += {"pwhash": $val}')"
+    echo "$system_json" > /run/system.json
+}
+
+if dmesg | grep -q QEMU || test -d /sys/module/qemu_fw_cfg; then
+    initctl cond set qemu
+    gen_qemu_system_file
+else
+    # NOTE: All this code will soon go away.
+    echo -e "\n\n\e[31mWARNING! Probe failed to get password hash from hardware\n" \
+            "Falling back to temporary hash\e[0m\n" > /dev/console
+    # Clear Test = admin
+    echo '{"pwhash": "$5$n2xoZAmITmPYjOTO$pbWHoa1Mu25a0e.akViAf9uWRvUgbq9BbcmzWWaNP0A"}' > /run/system.json
 fi
+
diff --git a/src/confd/bin/bootstrap b/src/confd/bin/bootstrap
--- a/src/confd/bin/bootstrap
+++ b/src/confd/bin/bootstrap
@@ -65,6 +65,12 @@ collate()
     fi
 }
 
+console_error()
+{
+    logger -p user.crit -t "BOOTSTRAP" "CRITICAL ERROR! $1"
+    echo -e "\n\n\e[31mCRITICAL BOOTSTRAP ERROR\n$1\e[0m\n" > /dev/console
+}
+
 factory()
 {
     gen=$1
@@ -76,6 +82,11 @@ factory()
     gen-hostname                                            >"$FACTORY_D/20-hostname.json"
     # shellcheck disable=SC2086
     gen-interfaces $GEN_IFACE_OPTS                          >"$FACTORY_D/20-interfaces.json"
+
+    if ! gen-admin-auth                             >"$FACTORY_D/10-authentication.json"; then
+        console_error "Unable to create factory config, gen-admin-auth failed"
+        return
+    fi
 
     [ -s "$FACTORY_D/20-hostkey.json"   ] || gen-hostkeys   >"$FACTORY_D/20-hostkey.json"
 
