confd: add support for upgrading container images
This patch adds a new CLI command 'container upgrade foo', where 'foo'
is the name of the container.  If more than one container use the same
image, multiple upgrades must be done because a container runs not on
the 'image:tag' but on the hash of the 'image:tag' it was created from.

Rename "done" queue to "active", since we want to recreate an active
container after fetching an updated base image.

Signed-off-by: Joachim Wiberg <troglobit@gmail.com>

diff --git a/board/common/rootfs/usr/sbin/container b/board/common/rootfs/usr/sbin/container
--- a/board/common/rootfs/usr/sbin/container
+++ b/board/common/rootfs/usr/sbin/container
@@ -246,6 +246,17 @@ case $cmd in
     stop)
 	initctl -bq stop "container:$1" || podman kill "$1"
 	;;
+    upgrade)
+	img=$(podman inspect "$1" | jq -r .[].ImageName)
+	if [ -z "$img" ]; then
+	    echo "No such container ($1), or invalid ImageName.  Cannot upgrade."
+	    exit 1;
+	fi
+	podman stop "$1"
+	podman pull "$img" || (echo "Failed fetching $img, check your network (settings)."; exit 1)
+	"/var/lib/containers/active/${1}.sh" || (echo "Failed recreating container $1"; exit 1)
+	echo "Container $1 recreated, restart with 'container start $1'"
+	;;
     volume)
 	cmd=$1
 	shift
