Fix container upgrade regression
In 0edc2d5 and afbe5ca, just prior to v24.06.0-rc1, support for deleting
containers in the background was added.  However, this also broke support
for upgrading containers.

In afbe5ca the start script for containers was renamed from NAME.sh to
S01-NAME.sh, but the container wrapper script's upgrade command was not
updated.  Neither was the cleanup and post-hook callbacks in confd!  So
when a container had been added to the system, the cleanup callback just
simply deleted the script, preventing it from being recreated at ugprade

This patch fixes the container identification code and also refactors
the execd code to ensure that kill scripts (for deleting in background)
and start scripts are run in the proper order *and* ensuring that execd
also does not accidentally remove the container start script.

Some cosmetic changes to the output at upgrade have also been added.

Fixes #623

Signed-off-by: Joachim Wiberg <troglobit@gmail.com>

diff --git a/board/common/rootfs/usr/sbin/container b/board/common/rootfs/usr/sbin/container
--- a/board/common/rootfs/usr/sbin/container
+++ b/board/common/rootfs/usr/sbin/container
@@ -626,20 +626,32 @@ case $cmd in
 	podman stats -i 2
 	;;
     upgrade)
+	# Start script used to initially create container
+	script=/var/lib/containers/active/S01-${1}.sh
+
+	# Find container image
 	img=$(podman inspect "$1" | jq -r .[].ImageName)
 	if [ -z "$img" ]; then
 	    echo "No such container ($1), or invalid ImageName.  Cannot upgrade."
 	    exit 1;
 	fi
+
+	# Likely an OCI archive, or local directory, assume user has updated image.
 	if echo "$img" | grep -Eq '^localhost/'; then
-	    # Likely an OCI archive, or local directory, assume user has updated image.
-	    file=$(awk '{s=$NF} END{print s}' "/var/lib/containers/active/${1}.sh")
+	    file=$(awk '{s=$NF} END{print s}' "$script")
 	    echo "Upgrading container ${1} with local archive: $file ..."
 	else
+	    printf ">> Stopping ... "
 	    podman stop "$1"
+	    printf ">> "
 	    podman pull "$img" || (echo "Failed fetching $img, check your network (settings)."; exit 1)
 	fi
-	"/var/lib/containers/active/${1}.sh" || (echo "Failed recreating container $1"; exit 1)
+	echo ">> Starting $1 ..."
+	if ! "$script"; then
+	    echo ">> Failed recreating container $1"
+	    exit 1
+	fi
+	echo ">> Done."
 	;;
     volume)
 	cmd=$1
